/**
 * Type declarations for Razorpay Checkout
 * Razorpay is loaded via script tag in index.html
 * @see https://razorpay.com/docs/payments/payment-gateway/web-integration/
 */

declare global {
  interface Window {
    Razorpay: typeof Razorpay;
  }
}

interface RazorpayOptions {
  /** The order ID generated by your server */
  order_id: string;
  /** Amount in smallest unit (e.g., paise for INR) */
  amount?: number;
  /** Currency code (e.g., INR) */
  currency?: string;
  /** Customer name */
  name?: string;
  /** Customer description */
  description?: string;
  /** Customer email */
  prefill?: {
    name?: string;
    email?: string;
    contact?: string;
  };
  /** Theme configuration */
  theme?: {
    color?: string;
    hide_topbar?: boolean;
    backdrop_color?: string;
    text_color?: string;
    primary_color?: string;
  };
  /** Notes (key-value pairs) */
  notes?: Record<string, string>;
  /** Modal configuration */
  modal?: {
    ondismiss?: () => void;
    escape?: boolean;
    confirm_close?: boolean;
    backdrop?: boolean | "static";
    animate?: boolean;
  };
  /** Handler for successful payment */
  handler?: (response: RazorpayPaymentResponse) => void;
  /** Handler for payment error */
  prefill?: {
    name?: string;
    email?: string;
    contact?: string;
  };
}

interface RazorpayPaymentResponse {
  /** Razorpay Payment ID */
  razorpay_payment_id: string;
  /** Razorpay Order ID */
  razorpay_order_id: string;
  /** Razorpay Signature */
  razorpay_signature: string;
}

interface RazorpayError {
  /** Error code */
  code: string;
  /** Error description */
  description: string;
  /** Source of error */
  source: string;
  /** Additional step */
  step: string;
  /** Error reason */
  reason: string;
  /** Metadata */
  metadata: {
    order_id: string;
    payment_id: string;
  };
}

interface RazorpayInstance {
  /** Opens the Razorpay checkout modal */
  open(): void;
  /** Closes the Razorpay checkout modal */
  close(): void;
  /** Hides the Razorpay checkout modal */
  hide(): void;
  /** Shows the Razorpay checkout modal */
  show(): void;
  /** Destroys the Razorpay instance */
  destroy(): void;
}

declare class Razorpay {
  constructor(options: RazorpayOptions);
  
  /** Opens the Razorpay checkout modal */
  open(): void;
  
  /** Closes the Razorpay checkout modal */
  close(): void;
  
  /** Hides the Razorpay checkout modal */
  hide(): void;
  
  /** Shows the Razorpay checkout modal */
  show(): void;
  
  /** Destroys the Razorpay instance */
  destroy(): void;

  /** Event handler for payment success */
  on(event: "payment.success", callback: (response: RazorpayPaymentResponse) => void): void;
  
  /** Event handler for payment failure */
  on(event: "payment.failed", callback: (response: { error: RazorpayError }) => void): void;
  
  /** Static method to open checkout */
  static open(options: RazorpayOptions): RazorpayInstance;
}

export { Razorpay, RazorpayOptions, RazorpayPaymentResponse, RazorpayError, RazorpayInstance };